name: Auto Deploy to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'nanny-match-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/backend
          ./auto-deploy.sh



